name: Yarn Build and Test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js and Yarn
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        registry-url: 'https://registry.yarnpkg.com'
        cache: 'yarn'
    
    - name: Install dependencies
      run: yarn install

    - name: Build
      run: yarn build
