name: Firebase Deploy

on:
  push:
    branches: 
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '17'
      - run: npm ci
      - run: npm run build
      - name: GitHub Action for Firebase
        uses: w9jds/firebase-action@v1.5.0
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}


# name: Firebase Deployment

# on:
#   push:
#     branches:
#       - master

# jobs:
#   build:
#     name: Build
#     runs-on: ubuntu-latest
#     steps:
#       - name: Use Node.js 18.x and Yarn
#         uses: actions/setup-node@v4
#         with:
#           node-version: 18.x
#           registry-url: https://registry.yarnpkg.com
#       - name: Checkout Repo
#         uses: actions/checkout@v2.4.4
#       - name: Install Dependencies with Yarn
#         run: |
#           yarn install
#       - name: Build
#         env:
#           CI: false
#         run: yarn run build
#       - name: Archive Production Artifact
#         uses: actions/upload-artifact@v2.2.4
#         with:
#           name: build
#           path: build

#   deploy:
#     name: Deploy
#     needs: build
#     runs-on: ubuntu-latest
#     steps:
#       - name: Download Artifact
#         uses: actions/download-artifact@v2
#         with:
#           name: build
#           path: build
#       - name: Deploy to Firebase
#         uses: w9jds/firebase-action@master
#         with:
#           args: deploy --only hosting
#         env:
#           FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
